//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int MailID { get; set; }
        public string SenderName { get; set; }
        public string SenderEmail { get; set; }
        public string SenderCellNo { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
    }
}
